//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web;
namespace PinProjekt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TBLartikli
    {
        [DisplayName("Šifra")]
        public int sifra { get; set; }
        
        [Required]
        [DisplayName("Naziv")]
        public string naziv { get; set; }

        [DisplayName("Cijena")]
        [Required]
        public Nullable<int> cijena { get; set; }

        [DisplayName("Količina")]
        [Required]
        public Nullable<int> kolicina { get; set; }

        [DisplayName("Opis")]
        public string opis { get; set; }
        
        [Required]
        [DisplayName("Slika")]
        public string slika { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageFile { get; set; }

    }
}
