//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinProjekt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TBLUserInfo
    {
        public int IdUs { get; set; }
    
        [Required(ErrorMessage ="Ovo polje je obavezno.")]
        [Display(Name ="Korisničko ime")]
        public string UsernameUs { get; set; }
        
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Ovo polje je obavezno.")]
        [Display(Name ="Lozinka")]
        public string PasswordUs { get; set; }
        
        // Dodajemo još jedno polje za potvrdu lozinke 
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Ovo polje je obavezno.")]
        [Display(Name = "Potvrdi Lozinku")]
        // ne želimo da nam stvara stupac u bazi sa ovim propertijem pa čemo staviti sljedeće
        [NotMapped]
        // tu odmah provjeravamo da li je lozinka ispravno potvrđena
        [Compare("PasswordUs",ErrorMessage ="Lozinka se ne poklapa!")]
        public string RePasswordUs { get; set; }
    }
}
